### ISSUE TITLE
Drag Dimensions and Metrics away from Columns or Rows Section

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#10]
Hi Prahlad,
Next challange:
- Could we drag the Items away from Columns and Rows section to remove them from the visualisation
- Could we have an automatic ordering of items in Columns and Rows section as following: Dimensions Metrics. For example, if the user drags on columns dimension1 then Metric1 then Dimension2 it will end up being: Dimension1, Dimension2, Sum(Metric1). If user drags over Dimension3 it will be Dimension1, Dimension2, Dimension3, Sum(Metric1) and NOT Dimension1, Dimension2, Sum(Metric1), Dimension3.
- Would it be possible to also drag and drop the order of dimensions and metrics within Columns and Rows manually?

Adding:
- Also drag dimensions and metrics from columns into rows and vice versa

**Comment by key2market** [comment]
Just added to the requirements:
"Also drag dimensions and metrics from columns into rows and vice versa"

**Comment by prahladyeri** [comment]
Fixed in master branch, feel free to reopen.

Please note that I've only sanity-tested this. Once date and number filters are implemented, I'll perform integration testing on all three and then push them to `v1.3` release.

**Comment by key2market** [comment]
Dragging country_id into Rows and then Dragging it back into Measures creates the following bug as per image.

![screen shot 2016-01-21 at 2 28 37 pm](https://cloud.githubusercontent.com/assets/16460237/12481731/60e50346-c04b-11e5-959b-7e6663a494b3.png)

**Comment by prahladyeri** [comment]
I've fixed this bug, however reordering is proving a bit tricky and needs some extensive digging into `jQuery-ui` API, so I'll fix them once all other bugs are fixed.

**Comment by key2market** [comment]
Once it is dragged away, it should disappear from the chart as well. Totally removed from the data viz.

**Comment by prahladyeri** [comment]
Sure thing, I just noticed. I'll fix it soon along with the #23 issue.

**Comment by prahladyeri** [comment]
Fixed in master branch and performed sanity testing. Feel free to retest and reopen.
