### ISSUE TITLE
Save the Visualization

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#11]
Could the user have a button at the top right corner of the chart that will allow him to save the chart (could be into MySQL or directory with user's ID). 
We want to save 2 things:
- Just the Visualization. This way user can embed this visualization with other Visualizations into a dashboard that can have 2 charts side by side and as many charts as the user wants to add. SO if the user wants to have 6 charts in the dashboards, there will be 3 rows of 2 charts per row. This dashboard will be a separate page.

- The whole editing environment (which columns are SUM, which ones are COUNT, chart preference, which ones are dimensions and which ones are metrics). This way, when the user wants to come back to this particular chart and edit it, it will appear to the user exactly as he left it last time.

**Comment by prahladyeri** [comment]
It could be saved only in a directory, mysql can store only queries, not the other information that is needed here. Will the default home directory where `CSV` is already saved do?

**Comment by key2market** [comment]
I think default home directory would be fine. But keep in mind that later, we would need to have different users login via WP login and they will have access to only their own dashboards and stuff

**Comment by prahladyeri** [comment]
> But keep in mind that later, we would need to have different users login via WP login and they will have access to only their own dashboards and stuff

No probs, it will be in the same directory as the chart app (`index.php`). If the WP user can access the chart, he/she can access the saved file too.

**Comment by key2market** [comment]
Thanks Prahlad,
Do you have experience with WP? Is that something you can orchestrate there too? Because we want to have centralised APP environment that will be accessible all registred users (index.php) but the unique reports they create should be saved in the user's profile rather than central repository.

Kirill

**Comment by prahladyeri** [comment]
> Do you have experience with WP? Is that something you can orchestrate there too?

Sure, I can convert this into a Wordpress plugin, depends on how you want to achieve the integration. Do you want the `k2m chart` as a separate reusable library that is called by the WP plugin, or would you like to just convert this entirely to a WP plugin which is just called from the WP admin area?

**Comment by key2market** [comment]
Hi Prahlad,
I am not sure it needs to be WP plugin but I do want to utilise WP login if possible and therefore give each user their own environment to create reports. I would not want to create a copy of the library for each user, but have one centralised core library. Yet have an opportunity for the user to save their work and put it together into a dashboard or set of dashboard. Do you understand what I mean? You can advise me here, but I don't think we need full blow WP plugin.

**Comment by prahladyeri** [comment]
Okay, I understand now, plugin is not at all needed if all you want is to just profile the chart data according to each user's WP_login. All we need to do here is fetch the currently logged in user from WP database and then save/get that user's chart data accordingly. But our chart app needs to store the credentials to WP database login in its config, so that it can access the current user info. Something like:

     host: localhost
     database: wpdata
     username: xyz
     password: xyz

Can we do that?

**Comment by key2market** [comment]
IT does not have to be WP database. The visualisation tool connects to any database with open JDBC connection and that connection is specific to each data source. I could have one chart pulling data from one table. Another chart pulling data from different database and different table, then third chart and so on. 
These can be stored in DB but there must be a linkage to the charts that are using them or they can be stored as part of the setting for each chart when user saves them

**Comment by prahladyeri** [comment]
> It does not have to be WP database. The visualisation tool connects to any database with open JDBC 

Agreed. I'm not talking about the `databases` our app connects to fetch the chart visualization data. I'm talking about the `database` that our app will  need to connect in order to fetch the currently logged in WP user.

Hope that makes sense.

**Comment by key2market** [comment]
sure, but current logged in user is handled via session. But to get user_id we would need to go back to localhost WP db. You are right. :)

**Comment by prahladyeri** [comment]
Fixed. Feel free to reopen. Things to note:

1. I haven't added any WP related feature just yet. Presently, the environment is saved to a file named `env.json` on the backend (the same location as your index.php is located).
2. Test the `Save` and `Restore` buttons and play with it. Please note that connection information isn't saved in the `json` file, only the visual areas you mentioned in the ticket. If you refresh, you will have to at least select a Table/CustomSQL again.
