### ISSUE TITLE
Error Passing from MySQL

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#17]
- If MySQL throws and error (for example, user connects to the table on which he has no permission) do we have a way to pass this MySQL error to the user?
- Is there a way to pass back MySQL errors with custom SQL?
- Why is attached SQL not correct?
![screen shot 2016-01-07 at 7 09 51 pm](https://cloud.githubusercontent.com/assets/16460237/12178550/5b910446-b572-11e5-96c8-8f514773b49b.png)

**Comment by prahladyeri** [comment]
Yes it is possible, I am presently sending only the error-code, not the full description. I 'll send description too. In this particular example, perhaps there is a typo in table/column name. Run it on the backend mysql and you will know.

**Comment by prahladyeri** [comment]
It now shows a proper `modal popup` with the SQL Error code, driver-specific error code and driver-specific description, Enjoy!

![bspopup_sql](https://cloud.githubusercontent.com/assets/5732256/12193416/262e7e18-b60e-11e5-876a-8e99e60d1122.png)

**Comment by prahladyeri** [comment]
Fixed. Feel free to test and reopen.
