### ISSUE TITLE
Add Filter Options 

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#18]
Bellow metrics, could we please add a box for the filters
1) Filters for dimensions: Will have 2 options:
2) The backend SQL query will fetch all distinct values for that particular field from the database and will present them to the user with checkboxes. There will be an exclude button that will specify if the filter is for these values or all values excluding these values.

![screen shot 2016-01-07 at 7 33 17 pm](https://cloud.githubusercontent.com/assets/16460237/12179294/403e44c0-b576-11e5-8228-db2e92532558.png)

b) wildcard query with freehand text that can be typed by the user.
![screen shot 2016-01-07 at 7 32 56 pm](https://cloud.githubusercontent.com/assets/16460237/12179321/592b91e0-b576-11e5-99cc-2379b22afcda.png)

2) Filter for metrics will allow user to filter out all values that match a particular criteria:
![screen shot 2016-01-07 at 7 33 44 pm](https://cloud.githubusercontent.com/assets/16460237/12179338/744ddee2-b576-11e5-8391-30c58e604a0f.png)
![screen shot 2016-01-07 at 7 41 18 pm](https://cloud.githubusercontent.com/assets/16460237/12179378/beb1b378-b576-11e5-93e0-112d6539241b.png)

Or it will apply on the calculated value such as SUM(revenue) < 200

3) Dates when user uses dates as a filter, they have the following options, which are then added to the query.
![screen shot 2016-01-07 at 7 34 03 pm](https://cloud.githubusercontent.com/assets/16460237/12179401/e32a98c8-b576-11e5-83ba-39d529aa9bc1.png)

**Comment by key2market** [comment]
Here is the video of how filters are working:
https://www.youtube.com/watch?v=rOZ1hN_Faek&feature=youtu.be

**Comment by prahladyeri** [comment]
Filters is presently ready only for strings, the number and date filters will follow shortly. Don't perform any acrobatic testing since it is only on unstable master yet, but you can perform sanity testing by placing various wildcard and general filters.

**Comment by prahladyeri** [comment]
@key2market The current master branch is still alpha and semi-tested, but I would still like you to test-drive it once and let me know if anything big and major is missing (don't worry about small issues like dialogs, typos, fonts, etc. those are still under active testing).

Please note that I haven't included all filter-types yet, only the major ones. This way, the impact of any drastic change would be minimal.

**Comment by prahladyeri** [comment]
I've tagged version 1.3 after some sanity testing:

https://github.com/key2market/dataviz/tree/v1.3

However, that doesn't mean that it will be 100% perfect and free of bugs (there is no such thing in Software Engineering). If you find a bug, let me know. I'll fix it and tag 1.4, 1.5, etc.. (that's what later versions are for :smile: ).

**Comment by prahladyeri** [comment]
I'm closing this as the general filter functionality is implemented. Specific glitches related to different types of filters are being handled by other open issues. Feel free to reopen, however.
