### ISSUE TITLE
Wrong Connection does not return error

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#19]
Hi Prahlad,
I have just tried to connect to Postgres server (I know that we don't have Postgres connection) and the popup was just stuck there not giving me any feedback on whether connection was successful or what error has the system encountered.

**Comment by key2market** [comment]
![screen shot 2016-01-09 at 8 05 19 pm](https://cloud.githubusercontent.com/assets/16460237/12217810/579edd86-b70c-11e5-96a0-99baf711a184.png)

**Comment by key2market** [comment]
And after this, the previous connection stopped working. I was not able to make graphs any more.

**Comment by prahladyeri** [comment]
In that case, just clear your browser cache and try again. It will remove the previous history.

**Comment by key2market** [comment]
I can't ask my users to refresh browser every time :) Is there no other option?

**Comment by prahladyeri** [comment]
Well, you should have asked me to test `postgres` connections earlier. I'd have tested and made changes appropriately. Try doing just Ctrl+F5 for a full refresh before clearing cache, that might work.

**Comment by prahladyeri** [comment]
Can you please checkout latest version v1.1 and test this ?

**Comment by prahladyeri** [comment]
Found fixed on master branch, hence closing. Feel free to reopen.
