### ISSUE TITLE
Editing a Filter

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#21]
-When I click on the filter in the Filters box to edit it, it opens a popup but the "button" inside the Filter Box disappears. It reappears again once I click Apply.
-Could we please reword the "Clear" into "Remove Filter"

For Metric Filter:
- when using numeric filter, like Country ID, We should add Exact Values to the option "Exact Values" after At Most. This should be tested as following, what if I want to filter only where country_id IN (1,5,12, 21)? I am not able to do that with the current options.

**Comment by prahladyeri** [comment]
@key2market 
Please confirm if the below screen conforms to what you want in the `Exact Values` tab:

![exact_values_tab](https://cloud.githubusercontent.com/assets/5732256/12521311/eae95afe-c16f-11e5-8fc8-6d6d31f1fdfe.png)

**Comment by prahladyeri** [comment]
Fixed in the latest master branch after `sanity testing`. Feel free to reopen.
