### ISSUE TITLE
Add Default Row Count

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#28]
Once the user creates a connection and connects to the table. Could we please create a custom dimension called Count All under Metrics that will basically be passing COUNT(*) to the backend if it is used?
For example, I would like to know how menu users I have per country. I connect to users table that has country column. I drag Country column to the Rows and then I drag Count All to the Columns and I basically get
SELECT country, COUNT(*)
FROM users
GROUP BY country

**Comment by prahladyeri** [comment]
Yep. I'm looking into this. Just one issue:

> SELECT country, COUNT()

I think you meant `COUNT(*)` there. `COUNT()` is a syntax error in most SQL dialects.

**Comment by key2market** [comment]
Yea, I meant count star :)
On Tue, Jan 26, 2016 at 3:19 PM Prahlad Yeri <notifications@github.com>
wrote:

> Yep. I'm looking into this. Just one issue:
>
> SELECT country, COUNT()
>
> I think you meant COUNT(*) there. COUNT() is a syntax error in most SQL
> dialects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/key2market/dataviz/issues/28#issuecomment-175036777>.
>
-- 

*Kirill Andriychuk*
CEO / Managing Director

Key2Market | A Business Intelligence Company

kirill@key2market.com

http://www.key2market.com/
___________________________________________________
Berlin: Richard-Sorge Str. 25 10249

Sofia: "Lulin" region, bl. 533, ent. B, unit 37

Registration Number: 203790364
Owner / Geschäftsführer: Kirill Andriychuk

**Comment by prahladyeri** [comment]
Hey Kirill, You can remove your personal info like signature, address, etc. when you reply to a `github` comment email (this is still an open-source project, I presume). I've edited your last comment and deleted that in this particular instance.

**Comment by prahladyeri** [comment]
Regarding:

> Could we please create a custom dimension called Count All

Are you sure it is a dimension and not a measure? Counts are generally measures, isn't it? I'm presently assuming it to be a measure for fixing this, reopen it if you feel otherwise.
