### ISSUE TITLE
Blank connection to database with no rights to see tables.

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#29]
When user connects to the database where the user has no rights on any tables, when clicking Connect the Data Sources windows shrinks without having any possibility to edit or add connection. See screenshots
![screen shot 2016-01-26 at 3 40 16 pm](https://cloud.githubusercontent.com/assets/16460237/12583727/71e220d2-c444-11e5-8b80-8609cdee4cf4.png)
![screen shot 2016-01-26 at 3 40 22 pm](https://cloud.githubusercontent.com/assets/16460237/12583730/74a7bd18-c444-11e5-85a1-7d799a054954.png)

**Comment by prahladyeri** [comment]
I'm working on this. As a time-being work-around, you can do a `shift-f5` and if that doesn't solve the problem, just open the console and type `localStorage.clear()`.

**Comment by prahladyeri** [comment]
Fixed this by adding an "Edit Connection" button to the Select Table dialog as shown below:

![edit_connection](https://cloud.githubusercontent.com/assets/5732256/12596708/33ed5da6-c4a7-11e5-95cf-89c0aa9a2d63.png)

**Comment by prahladyeri** [comment]
I'll also add a validation so that the "Connect" won't happen in case there are zero tables.

**Comment by prahladyeri** [comment]
Fixed, added validation for zero tables,  and sanity tested.
