### ISSUE TITLE
Add Pause/Resume button to Viz

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#30]
Add a button at the top right side of the chart to pause querying the database until the layout has been built. This way user can first set up all the metrics and dimensions he/she wants and then execute the query.

**Comment by prahladyeri** [comment]
PFA the short screencast to see the pause button in action. Closing this as fixed.
[pause_button.webm.zip](https://github.com/key2market/dataviz/files/110316/pause_button.webm.zip)
